- Scenes/Monsters/Slime.tscn
- Scenes/Player/Player.tscn
- Scripts/Player/Player.gd
- project.godot
Updated Running and Idle animations to use the Animation Tree and Animation Player as opposed to the animated Sprite object.
> Update running and idle animations to use Animation Player and Animation tree

- Scenes/Monsters/Slime.tscn
- Scenes/Player/Player.tscn
- Scripts/Player/Player.gd
- Update attack animation to be part of the animation tree
- Update hitbox to hit slimes
- slimes die when sliced!
https://user-images.githubusercontent.com/44471274/170124833-1349b3dc-18e7-4795-a3d2-6ae364732437.mov
> Update animation tree to have attack

- Scenes/Player/Player.tscn
> Fix PC run direction bug

- game_state.gd
- Loads/save to file and sets back the current game state (Stats)
- Need to expand as we have more state we want to save
> Basic game state saving function

- Scripts/Enemy.gd
> Makes following enemies to stop moving when they reached the player

- Scenes/Monsters/Bat.tscn
- Scenes/Monsters/Slime.tscn
- Scripts/Entity/Enemy.gd
> Stop zones for chasing

- Scenes/Player/Attacks/Energyball.tscn
- Scripts/Entity/Attacks/Energyball.gd
- Scripts/Entity/Player.gd
Fixed attack direction for the spell, you can shoot left and right.
https://user-images.githubusercontent.com/44471274/170554046-b97bd4a1-848f-452c-a584-6d06d3938cd2.mov
> Fix attack directions for the spell

- game_state.gd
> Unpause when there is no additional dialog

- Scenes/Monsters/Bat.tscn
- Scenes/Monsters/Slime.tscn
- Scenes/Player/Attacks/Energyball.tscn
- Scenes/Player/Player.tscn
- Scenes/SceneChanger.tscn
Fixed attack / spell attack layering to not hit the environment anymore
https://user-images.githubusercontent.com/44471274/170720232-d118dd60-2c9c-4712-9bc5-bc70fe779eab.mov
.
> Fix light-attack and spell-attack layering

- Dialogue/Doug.tres
- Scenes/Dialogue/example_balloon.gd
- Scenes/Dialogue/menu.tscn
- game_state.gd
First draft of the dialogue from Doug. He acts as a tutorial
> Doug dialogue

- Scenes/Npc/Sprite_MaleTownsperson.tscn
- Scenes/Town.tscn
I added him! He can talk! Now to get down to business
> [npc] make graybeard speak

- Scenes/InteractableObjects/Doug.tscn
- Scenes/InteractableObjects/LordGraybeard.tscn
- Scripts/InteractableObjects/LordGraybeard.gd
> fix bug related to path

- Scenes/Monsters/Bat.tscn
- Scenes/Player/Player.tscn
- Scenes/UI/HealthUI.tscn
- Scripts/Entity/Enemy.gd
- Scripts/Entity/Entity.gd
- Scripts/Entity/Player.gd
- project.godot
- moved knockback to Entity
- enemies no longer subscribing to the no-health signal of player
- bats can now hit the player and decrease the health
- to replicate for other monsters, adding a collision shape with
the layer 15 (Monster) enabled is enough
> Bats can attack you

- Scenes/Monsters/AdeptNecromancer.tscn
- Scenes/Monsters/Bat.tscn
- Scenes/Monsters/CorruptedTreant.tscn
- Scenes/Monsters/DeftSorceress.tscn
- Scenes/Monsters/EarthElemental.tscn
- Scenes/Monsters/ExpertDruid.tscn
- Scenes/Monsters/FireElemental.tscn
- Scenes/Monsters/FleshGolem.tscn
- Scenes/Monsters/FlutteringPixie.tscn
- Scenes/Monsters/GelatinousCube.tscn
- Scenes/Monsters/GlowingWisp.tscn
- Scenes/Monsters/GrandmasterWarlock.tscn
- Scenes/Monsters/GrizzledTreant.tscn
- Scenes/Monsters/HungeMimic.tscn
- Scenes/Monsters/IceGolem.tscn
- Scenes/Monsters/IronGolem.tscn
- Scenes/Monsters/NovicePyromancer.tscn
- Scenes/Monsters/SkilledBattleMage.tscn
- Scenes/Monsters/Slime.tscn
- Scenes/Monsters/VenonmousChimera.tscn
- Scenes/Monsters/VileWitch.tscn
- Scenes/Monsters/WaterElemental.tscn
so that they can inflict damage upon collition.
> Adds the monster layer to other monsters

- Scripts/Entity/Entity.gd
- Scripts/Entity/Player.gd
- to be able to use it for the magic missile and idle
> Store the facing direction

- Scenes/Graveyard.tscn
- Scenes/Town.tscn
They fit so well!
Need to make them move and interact. To wander, maybe just use the enemy script on idle?
> Added NPC to Town and Graveyard

- Dialogue/VarLogMessages.tres
> [dialogue] add boss dialogue

- Scenes/Crypt.tscn
- Scenes/Graveyard.tscn
- Scenes/Sea.tscn
- Scenes/Town.tscn
Set the background music to run even when the game is paused.
Also quieted it down a little bit
> [task] fix background music pauses

- Scenes/Game.tscn
- Scenes/UI/HelpMenu.tscn
- Scripts/Game.gd
- Scripts/UI/HelpMenu.gd
This help *barely* works. You can hit ESC for it to pop up, but it's in the wrong spot. It also won't go away unless you click in the window. Ain't got time to figure it out, but at least we have it now
> add a help menu

- Dialogue/introduction.tres
- Scenes/Cutscenes/Introduction.tscn
- Scenes/Dialogue/IntroBalloon.tscn
- Scenes/FadeOut.tscn
- Scenes/title_screen.tscn
- Scripts/Cutscenes/Introduction.gd
- Scripts/FadeOut.gd
> add an introduction scene

- Scenes/title_screen.tscn
You can skip the intro with this
> wire up the continue button

- Scenes/Graveyard.tscn
- Scripts/InteractableObjects/Interactable.gd
- Scripts/InteractableObjects/PortalArea2D.gd
- project.godot
> Made Portal show interact tooltip

- Scenes/Player/Player.tscn
- Scripts/Entity/Player.gd
- no more "whoosh" when the game starts
- added the "whoosh" to the player attack
> [fix] player audio stream update

- game_state.gd
> Increased max health by 1

- Scenes/Buttons/ExitButton.tscn
- Scenes/death_screen.tscn
> Death screen
